apiVersion: v1
kind: Service
metadata:
  name: oficina-api
  namespace: oficina
  labels:
    app: oficina-api
spec:
  type: NodePort
  selector:
    app: oficina-api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
